pipeline/compilers/sass.py

Make the SASS compiler compatible with libsass-python

---

pipeline/storage.py

https://github.com/cyberdelia/django-pipeline/issues/394
TL;DR Setting a default location like this causes breakage and isn't the
responsibility of `PipelineMixin`

Remove tempdir storage location

---

docs/compilers.rst
pipeline/compilers/es6.py
pipeline/conf.py

This allow to use [6to5](http://6to5.org), to compile ES6 code (with extension ``.es6``) to ES5 code (with extension ``.js``).

Add ES6 support via 6to5.

---

pipeline/finders.py

Some third party js/css libraries installed through bower, contain
broken references in CSS: url(...). When using PipelineCachedStorage,
this breaks during collectstatic. As with AppDirectoriesFinder, ignore
CSS. CSS is a pielinable content that can be managed through a
pipeline asset.
This brings FileSystemFinder inline with AppDirectoriesFinder.
True, these CSS fixes should be fixed in their respective
projects. Bugs have been filed, but this fix will allow pipeline users
to continue using third party libraries without breaking builds and
deployment.

Add missing ignore_pattern to FileSystemFinder.

---

pipeline/finders.py

Recent change of `PipelineFinder` breaks static collection with `PIPELINE_ENABLED = False` which is preferred for development.
`PipelineFinder.list` should still return empty list as it was in previous versions.
With standard list of finders:
```
STATICFILES_FINDERS = (
'django.contrib.staticfiles.finders.FileSystemFinder',
'django.contrib.staticfiles.finders.AppDirectoriesFinder',
'pipeline.finders.PipelineFinder',
'pipeline.finders.CachedFileFinder',
)
```
and empty list from `PipelineFinder` everything works ok for both `PIPELINE_ENABLED` `True` and `False`.
Otherwise `return super(PipelineFinder, self).list(ignore_patterns)` leads to extra static file copies after each `collectstatic` invocation if current storage is "cached" (e.g. `STATICFILES_STORAGE = …

PipelineFinder.list should always return empty list

---

pipeline/compilers/less.py

Makes it work with bootstrap 3. See http://stackoverflow.com/questions/28475730/compiling-bootstrap-less-shows-errors-warnings

Let pipe lessc output to outfile rather than providing outfile arg due to lessc bug

---

AUTHORS
pipeline/compressors/__init__.py
tests/assets/css/urls.css
tests/tests/test_compressor.py

Pipeline was ignoring HTML anchor tags as valid URLs, and would erroneously prepend a relative directory path to the anchor tag.
This fix adds the octothorpe (#) to the constant NON_REWRITEABLE_URL to allow the anchor tag to be ignored as a valid URL link.

Add '#' to constant NON_REWRITEABLE_URL

---

docs/using.rst

mollyproject.org appears to be occupied by a squatter. link directly to the GH project instead.

Correct link to the Molly Project.

---

pipeline/storage.py

Not accepting this arg is pending deprecation in Django 1.8.

Add max_length arg to PipelineStorage.get_available_name.

---

tests/tests/test_compressor.py

sometimes when a execute a test i get a error when open a css with unicode, this fix the problem

add econding to open

---

tests/settings.py

warning in 1.9
RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.

add templates to test pipeline

---

pipeline/compressors/__init__.py
tests/assets/js/first.js
tests/assets/js/second.js
tests/tests/test_compressor.py

Most JavaScript packages wrap their code in IIFEs, which is good.
Pipeline used to concatenate JS only with a newline. That can break those IIFES
though:
(function() {
// package A
}()) // No semicolon! Most people put one here, but unfortunately not all!
(function() {
// package B
}());
The above is equivalent to:
(function() {
// package A
}())(function() {
// package B
}());
Suddenly we have a function call!
With this commit, JS is concatenated with a newline followed by a semicolon,
which fixes the above issue:
(function() {
// package A
}()) // No semicolon! Most people put one here, but unfortunately not all!
;(function() {
// package B
}());
There is no need to worry about superfluos semicolons, such as:
(function() {
// package A
}());
;;(function() {
// package B
}());
That is …

Safely concatenate JavaScript

---

AUTHORS
docs/configuration.rst
pipeline/compressors/__init__.py

Fixed bug when wrapped javascript code ends with one-line comment.
Obviously, this causes syntax error.

Fix for wrapping javascript code.

---

docs/usage.rst

I feel this makes it easy to understand how to pass `pipeline.templatetags.ext.PipelineExtension` into jinja2 environment. I've added updated default jinja2 config for django, so most of the people should be familiar with it.

Docs update: Configuration example for jinja2

---

docs/configuration.rst

In headings and one non-heading. This is probably a leftover after some semi-automated way of removing that `PIPELINE_` prefix.

Fix literal markup for settings

---

pipeline/conf.py

The 1.6.1 release added a dependency on the `setting_changed` signal. In Django
releases prior to 1.8, this signal is located in the `django.test.signals`
module, and in 1.8, an alias was added in `django.core.signals`.
This change adds a fallback import to restore compatibility with older versions
for applications which cannot (yet) migrate to the newer Djangos. It has been
tested against Django 1.6.11 and 1.8.9.

Fix compatibility with Django < 1.8

---

pipeline/glob.py
tests/tests/test_glob.py
tests/tests/test_storage.py

Commit bd6b9d8 dramatically changed the way that files are loaded, and had the
side-effect of filtering out any files which were sourced by finders outside of
the main `STATICFILES_DIRS`.
In the case I'm trying to address, we have an extension framework (in Review
Board and Djblets) which can load static media from third-party packages which
are activated at runtime. This media is loaded by instantiating
`StylesheetNode` and `JavascriptNode` from `pipeline.templatetags` in
combination with a special finder. Because django-pipeline no longer uses
finders before the compile stage, calling `storage.exists` (via
`Package.sources` -> `glob`) silently filters these out.
Inside `glob`, I agree that it's useful to test existence when trying to expand
`*` or `?`, but when the path is just a normal …

Don't filter out "missing" files in the glob stage.

---

pipeline/compilers/__init__.py

Depending on where an exception is raised inside a compiler's
`execute_command`, the `stdout` variable may not be assigned. In this case, the
finally handler would fail with an `UnboundLocalError`, hiding the true cause
of the exception. This change adds a new variable, `stdout_name`, which is
populated once we've actually created the file. After this, the `CompilerError`
is successfully raised with the contents of the true error.

Fix an UnboundLocalError if a compiler fails.

---

pipeline/compilers/__init__.py
tests/tests/test_compiler.py

The current logic for compilers to manipulate output paths is pretty simple,
using `os.path.splitext` and the compiler's `output_extension`. This precludes
doing fancier things by just implementing one's own compiler class.
This change moves the `output_file` method into the CompilerBase class, so that
subclasses can override its behavior to suit their own needs.

Allow compilers to override output_path.

---

pipeline/compilers/__init__.py

The check to see whether or not a source file is outdated was being passed the
`input_path` and `output_path` variables, which are not the actual paths to
files on disk. In particular, `input_path` is the path which will be searched
for using the staticfiles finders, and `output_path` is the relative path
within the staticfiles root. If the staticfiles root was not the same as the
root directory of the project, this would result in the check always reporting
that the file was outdated. In addition, if a source file required a finder to
locate, the check would fail.
Changing this to use `infile` and `outfile` instead means that the check
operates on the same file paths that the compiler will. This therefore checks
the files that were copied by the collector against the files which are …

Fix paths given to compiler.is_outdated.

---

.travis.yml
tests/tests/test_storage.py
tests/utils.py
tox.ini

Support for 1.7 is pretty effortless after #536.
Support for 1.6 is more tricky and involves adding a missing class (`modify_settings`).

Add support for older Djangos

---

docs/configuration.rst
pipeline/compilers/__init__.py
pipeline/conf.py
pipeline/exceptions.py
pipeline/jinja2/__init__.py
pipeline/templates/pipeline/compile_error.html
pipeline/templatetags/pipeline.py
tests/tests/test_compiler.py

Debugging CSS/JavaScript compilation errors can be difficult when viewed
within the context of a Django error page, and if there's a wider
problem with other CSS/JavaScript packages, they won't show up until the
first compilation error is fixed. This is worse if running in a mode
where Pipeline is running but Django error pages aren't being shown.
This change introduces an option, `PIPELINE.SHOW_ERRORS_INLINE` (now
enabled by default) that outputs any compilation errors at the top of
the page, visually distinguished from the rest of the page, and
containing information on the failing package, command line, and output.
This makes it much easier to debug what went wrong.
The errors are outputted into a hidden div, and then once the page has
fully loaded, they're placed at the top. This …

Add error output for compiler errors within the browser.

---

docs/compilers.rst

This adds one line to the ES6 compilers section, which notes that the `.es6` file extension is required. This was not immediately apparent to me, and the line would have saved some frustration.
fixes #550

Adds documentation regarding ES6 config

---

pipeline/collector.py
pipeline/views.py
tests/tests/__init__.py
tests/tests/test_collector.py
tests/tests/test_views.py

In a Django development setup, it's common to have a `/static/` URL set up
to serve static media to the browser upon request. That's usually set to
either serve out of a specific directory or out of any configured
finders. However, the former doesn't guarantee any referenced files were
collected first, and the latter only considers source files (for the
purposes of timestamp calculation/caching) and not the
collected/compiled files.
This change introduces a new view, meant for use with Django's static
serving view, that will collect the referenced file before serving it,
guaranteeing that media like images and fonts are present.
To ensure that this view will return content quickly (especially
considering it will serve up any files referenced by the template tags),
an optimization was made …

Add a view for collecting static files before serving them.

---

docs/configuration.rst
pipeline/compressors/__init__.py
pipeline/conf.py

For my application, I would like to wrap each JS file in a custom error handler but there's no nice way to change the JS wrapper right now. I made a new setting called `JS_WRAPPER` which defaults to the current wrapper code.

Make the JS wrapper configurable

---

README.rst
docs/compressors.rst
docs/usage.rst

As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.

Convert readthedocs links for their .org -> .io migration for hosted projects

---

AUTHORS
pipeline/compilers/__init__.py
tests/tests/test_compiler.py

`argument_list` does not check if the first element is empty, which is problematic because, [by default](https://docs.python.org/3/library/subprocess.html#popen-constructor), that is the program that will be executed by `subprocess.Popen`, so, for example, if the first element in `argument_list` is an empty string, then a `PermissionError` will be raised. This came up when working with [django-pipeline-browserify](https://github.com/j0hnsmith/django-pipeline-browserify), because the first element in the command `BrowserifyCompiler` passes to `execute_command` is `BROWSERIFY_VARS`, which defaults to `''`. This commit will filter out empty elements in `argument_list` to prevent issues like this.

Remove empty args from argument_list in SubprocessCompiler

---

.travis.yml
AUTHORS
pipeline/collector.py
pipeline/middleware.py
tests/utils.py
tox.ini

I have not seen any Django 1.10 stuff yet, so I took the liberty of adding some envs for tox and travis CI. I also added support for Django 1.10's new style middleware and fixed some deprecation warnings.

Start Django 1.10 compatibility

---

pipeline/collector.py
tests/tests/test_collector.py

A commit made in 1.6.10 (ae6b3f8eaedffaf09860386c69763ead5a43c94d)
changed a storage lookup to use the prefixed_path variable instead of
the path variable when looking up modification times in order to
determine if an existing collected file should be deleted and
re-collected. By using the wrong path variable, the storage lookups
always failed, resulting in every single file being re-collected every
single time.
This reduces performance considerably, particularly with large codebases.
Since every file ends up copied, they appear as new and are recompiled.
This can result in very long page reloads on a development server,
especially if working on an older machine, in a VM, on a shared
filesystem, or on the Linux subsystem for Windows.
This is a simple change that fixes the lookup to use …

Fix a regression in determining when to collect static files.

---

docs/usage.rst
pipeline/forms.py
tests/tests/test_forms.py

Django allows forms and widgets to define the CSS or JavaScript files
needed on the page, automatically including those files in the
administration UI. This works fine for standalone media files, but
weren't an option for Pipeline packages.
This change introduces a branch new `PipelineFormMedia` class that a
form or widget's Media class can inherit from. The Media class can then
define `css_packages` or `js_packages` attributes that work just like
the standard `css`/`js` attributes but reference package names instead
of individual files.
Upon accessing the `css`  or `js` attributes, the files defined in the
packages will be collected/processed just like with the template tags
and the resulting filenames returned for use in the page.
Using this, any page compatible with Django's form media …

Add support for using Pipeline CSS/JS packages in forms and widgets.

---

pipeline/templatetags/pipeline.py

If compile error happens, we cannot see it. Instead, ‘context must be a dict rather than Context’.
Django 1.11. Regarding to docs, the same down to 1.7.

Fix to view compile error if happens.

---

pipeline/compilers/__init__.py

Replace os.rename with shutil.move, as it raises a FileExistsError on Windows.
See:
- http://stackoverflow.com/a/8107391
- https://docs.python.org/2/library/os.html?highlight=os.rename#os.rename

Replace os.rename with shutil.move

---

pipeline/compressors/__init__.py
tests/assets/css/urls.css
tests/tests/test_compressor.py

Suggested fix for #615 
As the reporter of the original issue I also spotted it when minifying bootstrap.
The regex proposed in issue report was breaking quote-less urls tests by stripping the first path component. I've fixed it and this now works for my case as well as suits the test cases.

Fix css url detector regex.

---

MANIFEST.in
README.rst
setup.py

Some small fixes before a 1.6.13 release:
- Add a code coverage badge to the readme, linking to [coveralls](https://coveralls.io/github/jazzband/django-pipeline).
- Add keywords to setup.py, so that a search for [django-pipeline on PyPI](https://pypi.python.org/pypi?%3Aaction=search&term=django-pipeline&submit=search) is more likely to find the package, and to make [pyroma](https://pypi.python.org/pypi/pyroma) happy.
- Update MANIFEST.in to make [check-manifest](https://pypi.python.org/pypi/check-manifest) happy.

Add coverage badge, update package

---

package.json
tests/assets/compressors/yuglify.js

npm was always installing the latest version of yuglify (now 1.0.1), but the cached expected test output was for version 0.1. I'm in favor of pinning the yuglify version to install so that the tests don't have to be fixed every time yuglify makes a change.

Fix tests to pass with yuglify 1.0.x

---

pipeline/compilers/__init__.py

Fixes #525. Do you also require tests or other stuff for this PR to be accepted?

Fix temporary file permissions

---

tests/settings.py

Tests are failing because google-closure has changed their installation path.

changed CLOSURE_BINARY to fix tests

---

AUTHORS
pipeline/templates/pipeline/css.html
tests/settings.py
tests/tests/test_template.py

The documentation for the [`extra_context`](https://django-pipeline.readthedocs.io/en/1.6.14/configuration.html#extra-context) option says:
> For CSS, if you do not specify extra_context/media, the default media in the <link> output will be media="all".
Related Issue: https://github.com/jazzband/django-pipeline/issues/684

Fixed a bug in css.html not defaulting media attribute to 'all'.

---

setup.py

I noticed that for my application running python 3.6 that installing `django-pipeline` was still installing `futures`, which is both not recommended and not needed. This PR modifies the setup arguments to match the [setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#id17) for declaring platform specific dependencies.
Let me know what you think and if there's anything else I can do here :)

use install_requires instead of extras_require

---

pipeline/compilers/__init__.py
setup.py

Use the file from the project to check outdated and as source for the compiler. This way the PIPELINE_COLLECTOR_ENABLED property can be set to False, which saves time during development.

Compile from project file

---

pipeline/middleware.py

Fix 691 - HTML not getting decoded properly by Middleware in Django 2.2

---

AUTHORS
docs/configuration.rst
pipeline/conf.py
tests/tests/test_utils.py

As noted in jazzband/django-pipeline#297 the mimetypes should not be `unicode` *on Python 2*. But they *should be `str`* on Python 3.
This fix ensures that `pipeline.utils.guess_type` only adds types and extensions as `str` to the core `mimetypes.types_map`.
Caused by: jazzband/django-pipeline#297
Effecting:
- pallets/werkzeug#636
- pallets/werkzeug#637

Keep mimetypes as str on all versions of Python

---

.travis.yml
HISTORY.rst
pipeline/storage.py
pipeline/templatetags/pipeline.py
setup.py
tests/tests/test_forms.py
tox.ini

Improvement to check Django version to prevent import errors in storage.py
Add Travis tests for Django 3.1 with python 3.6, 3.7, 3.8 and pypy3.
Change tests after an undocumented change in Media.render_js from Django
Related issue: https://code.djangoproject.com/ticket/31892

Add complet support for Django 3.1

---

pipeline/signals.py
pipeline/utils.py

Fixes this deprecation warnings from django:
- RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str()
- RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.

Fix deprecation warnings from Django

---

AUTHORS
docs/compressors.rst
package.json
pipeline/compressors/terser.py
pipeline/conf.py
tests/assets/compressors/terser.js
tests/settings.py
tests/tests/test_compressor.py

Add [terser](https://github.com/terser/terser) as a JS compressor which can handle both ES5 and ES6 syntax.

Add terser (JS compressor for ES5 and ES6)

---

.github/workflows/test.yml
tox.ini

See the individual commits, but basically this PR improves the Python/Django version testing matrix by:
- Ensure we're not testing unsupported Python/Django combinations (eg. Django's `main` branch doesn't need to be tested against Python 3.6 since the [minimum supported version is 3.8](https://docs.djangoproject.com/en/dev/faq/install/#what-python-version-can-i-use-with-django))
- Start testing Django's `main` and `4.0.x` branch against Python 3.10
- Separately test Django `4.0.x` from it's `main` branch (since they have now diverged)
- Merged in change from #761 changing the deprecated `pypy3` to `pypy-3.8`
Currently `django-pipeline` fails against the `4.0.x` and `main` branch, I'm going to push a separate PR (#760) which should fix all the issues (and remove `dj40` from tox's …

Update testing matrix

---

pipeline/packager.py

This patch resolves the problem by copying the compiled file into the packager (s3) storage.

Improved packager.compile() to handle s3 storage when compiler generates output to the local one.

---

CONTRIBUTING.rst
docs/using.rst

There are small typos in:
- CONTRIBUTING.rst
- docs/using.rst
Fixes:
- Should read `recommend` rather than `reccomend`.
- Should read `platform` rather than `plaform`.
- Should read `dependencies` rather than `depencies`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

AUTHORS
setup.py
tox.ini

In these two commits, we dropped Python 3.6 from GitHub action. [link1](https://github.com/jazzband/django-pipeline/commit/d4ab608597ab5f918575dc2f4239faa9d3a57fe5) [link2](https://github.com/jazzband/django-pipeline/commit/fa5aea3e4ca1b2b991b682ad20f1aa23f180d9a2)
But it was still in `tox` and `setup.py` files.

Remove Python 3.6 from tox and setup.py

---

HISTORY.rst
docs/compilers.rst
package.json
pipeline/compilers/typescript.py
pipeline/conf.py
tests/assets/compilers/typescript/expected.js
tests/assets/compilers/typescript/input.ts
tests/settings.py
tests/tests/test_compiler.py

TypeScript is used more frequently these days and I thought it could be a good feature for Pipeline to support its compiler.
- Add TypeScript compiler support
- Add test for TypeScript Compiler
- Update compilers documentation
- Update HISTORY.rst

Add TypeScript compiler support

---

.gitignore

When running tests locally npm creates a `package-lock.json` to lock the package's version, and because creates it in the root directory and we are using it for testing only I put it in the `.gitignore` file.

Add npm package-lock.json to gitignore

---

docs/conf.py
pipeline/collector.py
pipeline/compilers/__init__.py
pipeline/compressors/__init__.py
pipeline/compressors/terser.py
pipeline/exceptions.py
pipeline/finders.py
pipeline/forms.py
pipeline/jinja2/__init__.py
pipeline/middleware.py
pipeline/packager.py
pipeline/storage.py
pipeline/templatetags/pipeline.py
setup.py
tests/settings.py
tests/tests/test_collector.py
tests/tests/test_compiler.py
tests/tests/test_compressor.py
tests/tests/test_conf.py
tests/tests/test_template.py
tests/tests/test_utils.py
tests/tests/test_views.py
tests/utils.py

Using `pyupgrade` to upgrade old syntax to Python 3.
- docs/conf.py
- pipeline/*
- tests/*
- setup.py

Upgrade syntax to Python 3 using `pyupgrade`

---

pipeline/collector.py

As of Python 3.6 default `dict` in Python is ordered by default and the use of `OrederedDict` isn't necessary.

Use dict instead of OrderedDict

---

docs/conf.py
pipeline/__init__.py

pkg_resources is removed from Python 3.12, and its use raises a warning.
importlib.metadata can be used to get distribution info.

avoid the use of pkg_resources when importlib.metadata is available

---

pipeline/templatetags/pipeline.py

- `logging.Logger.warn()` has been deprecated since Python 3.3 and will not be available in Python 3.13 as per this pull request (https://github.com/python/cpython/pull/105377).

Replace deprecated .warn() method with .warning()

---

pipeline/templates/pipeline/compile_error.html
pipeline/templatetags/pipeline.py

The compiler error output that's injected into the page hard-codes a background color of white, but didn't hard-code a corresponding text color. If the page had set a default text color that was too close to white, it would be hard or impossible to read without selecting the text on the page.
This change addresses this by hard-coding a text color of black, ensuring it can be read.
It also goes a step further and improves the display when dealing with ANSI escape sequences in the error output, making it difficult to read through or copy/paste meaningful results. We now apply a common regex for stripping away any typical ANSI escape sequences we should expect in such output, leaving behind only the plain text content.
Triggered a compilation error on a page that had a default text color of …

Ensure correct compiler error styling and strip ANSI escape sequences.
